### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by oujinlong** [hailstorm350/pgobjc#1]
excuseme , thanks 4 this,but i built failed ...
"GPBProtocolBuffers_RuntimeSupport.h" not found..
How can i deal with ..?
thanks

**Comment by hailstorm350** [comment]
@oujinlong this repo was just started yesterday and a work in progress.

That said, if you're wanting a starting place with the protos to work on, I've updated the README with the following: make sure to `git pull && git submodule sync && git submodule update --init --recursive`
